/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 39.4.13 Thu Jun 11 22:40:55 2026.
 */

#include <string.h>

#include "ipc_vcu_zrd.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

int ipc_vcu_zrd_ipc_207_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_207_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->epb1_fault, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->epb2_fault, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->epb_fkd_sts, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u32(src_p->rl_wheel_speed, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->rl_wheel_speed, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->rl_wheel_speed, 16u, 0x01u);
    dst_p[5] |= pack_left_shift_u32(src_p->rr_wheel_speed, 1u, 0xfeu);
    dst_p[6] |= pack_right_shift_u32(src_p->rr_wheel_speed, 7u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->rr_wheel_speed, 15u, 0x03u);

    return (8);
}

int ipc_vcu_zrd_ipc_207_unpack(
    struct ipc_vcu_zrd_ipc_207_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->epb1_fault = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->epb2_fault = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->epb_fkd_sts = unpack_right_shift_u8(src_p[2], 0u, 0x01u);
    dst_p->rl_wheel_speed = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->rl_wheel_speed |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->rl_wheel_speed |= unpack_left_shift_u32(src_p[5], 16u, 0x01u);
    dst_p->rr_wheel_speed = unpack_right_shift_u32(src_p[5], 1u, 0xfeu);
    dst_p->rr_wheel_speed |= unpack_left_shift_u32(src_p[6], 7u, 0xffu);
    dst_p->rr_wheel_speed |= unpack_left_shift_u32(src_p[7], 15u, 0x03u);

    return (0);
}

int ipc_vcu_zrd_ipc_207_init(struct ipc_vcu_zrd_ipc_207_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_207_t));

    return 0;
}

uint8_t ipc_vcu_zrd_ipc_207_epb1_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_207_epb1_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_207_epb1_fault_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_207_epb2_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_207_epb2_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_207_epb2_fault_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_207_epb_fkd_sts_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_207_epb_fkd_sts_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_207_epb_fkd_sts_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint32_t ipc_vcu_zrd_ipc_207_rl_wheel_speed_encode(double value)
{
    return (uint32_t)((value - -655.0) / 0.01);
}

double ipc_vcu_zrd_ipc_207_rl_wheel_speed_decode(uint32_t value)
{
    return (((double)value * 0.01) + -655.0);
}

bool ipc_vcu_zrd_ipc_207_rl_wheel_speed_is_in_range(uint32_t value)
{
    return (value <= 131071u);
}

uint32_t ipc_vcu_zrd_ipc_207_rr_wheel_speed_encode(double value)
{
    return (uint32_t)((value - -655.0) / 0.01);
}

double ipc_vcu_zrd_ipc_207_rr_wheel_speed_decode(uint32_t value)
{
    return (((double)value * 0.01) + -655.0);
}

bool ipc_vcu_zrd_ipc_207_rr_wheel_speed_is_in_range(uint32_t value)
{
    return (value <= 131071u);
}

int ipc_vcu_zrd_ipc_206_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_206_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->ml_motor_torque, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->ml_motor_torque, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->mr_motor_torque, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->mr_motor_torque, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->rl_motor_torque, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->rl_motor_torque, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->rr_motor_torque, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->rr_motor_torque, 8u, 0xffu);

    return (8);
}

int ipc_vcu_zrd_ipc_206_unpack(
    struct ipc_vcu_zrd_ipc_206_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->ml_motor_torque = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->ml_motor_torque |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->mr_motor_torque = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->mr_motor_torque |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->rl_motor_torque = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->rl_motor_torque |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->rr_motor_torque = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->rr_motor_torque |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int ipc_vcu_zrd_ipc_206_init(struct ipc_vcu_zrd_ipc_206_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_206_t));

    return 0;
}

uint16_t ipc_vcu_zrd_ipc_206_ml_motor_torque_encode(double value)
{
    return (uint16_t)((value - -2000.0) / 0.1);
}

double ipc_vcu_zrd_ipc_206_ml_motor_torque_decode(uint16_t value)
{
    return (((double)value * 0.1) + -2000.0);
}

bool ipc_vcu_zrd_ipc_206_ml_motor_torque_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ipc_vcu_zrd_ipc_206_mr_motor_torque_encode(double value)
{
    return (uint16_t)((value - -2000.0) / 0.1);
}

double ipc_vcu_zrd_ipc_206_mr_motor_torque_decode(uint16_t value)
{
    return (((double)value * 0.1) + -2000.0);
}

bool ipc_vcu_zrd_ipc_206_mr_motor_torque_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ipc_vcu_zrd_ipc_206_rl_motor_torque_encode(double value)
{
    return (uint16_t)((value - -2000.0) / 0.1);
}

double ipc_vcu_zrd_ipc_206_rl_motor_torque_decode(uint16_t value)
{
    return (((double)value * 0.1) + -2000.0);
}

bool ipc_vcu_zrd_ipc_206_rl_motor_torque_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ipc_vcu_zrd_ipc_206_rr_motor_torque_encode(double value)
{
    return (uint16_t)((value - -2000.0) / 0.1);
}

double ipc_vcu_zrd_ipc_206_rr_motor_torque_decode(uint16_t value)
{
    return (((double)value * 0.1) + -2000.0);
}

bool ipc_vcu_zrd_ipc_206_rr_motor_torque_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ipc_vcu_zrd_ipc_205_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_205_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->mr_wheel_speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->mr_wheel_speed, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->mr_wheel_speed, 16u, 0x01u);
    dst_p[4] |= pack_left_shift_u16(src_p->fl_motor_torque, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->fl_motor_torque, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->fr_motor_torque, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->fr_motor_torque, 8u, 0xffu);

    return (8);
}

int ipc_vcu_zrd_ipc_205_unpack(
    struct ipc_vcu_zrd_ipc_205_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->mr_wheel_speed = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->mr_wheel_speed |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->mr_wheel_speed |= unpack_left_shift_u32(src_p[2], 16u, 0x01u);
    dst_p->fl_motor_torque = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->fl_motor_torque |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->fr_motor_torque = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->fr_motor_torque |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int ipc_vcu_zrd_ipc_205_init(struct ipc_vcu_zrd_ipc_205_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_205_t));

    return 0;
}

uint32_t ipc_vcu_zrd_ipc_205_mr_wheel_speed_encode(double value)
{
    return (uint32_t)((value - -655.0) / 0.01);
}

double ipc_vcu_zrd_ipc_205_mr_wheel_speed_decode(uint32_t value)
{
    return (((double)value * 0.01) + -655.0);
}

bool ipc_vcu_zrd_ipc_205_mr_wheel_speed_is_in_range(uint32_t value)
{
    return (value <= 131071u);
}

uint16_t ipc_vcu_zrd_ipc_205_fl_motor_torque_encode(double value)
{
    return (uint16_t)((value - -2000.0) / 0.1);
}

double ipc_vcu_zrd_ipc_205_fl_motor_torque_decode(uint16_t value)
{
    return (((double)value * 0.1) + -2000.0);
}

bool ipc_vcu_zrd_ipc_205_fl_motor_torque_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t ipc_vcu_zrd_ipc_205_fr_motor_torque_encode(double value)
{
    return (uint16_t)((value - -2000.0) / 0.1);
}

double ipc_vcu_zrd_ipc_205_fr_motor_torque_decode(uint16_t value)
{
    return (((double)value * 0.1) + -2000.0);
}

bool ipc_vcu_zrd_ipc_205_fr_motor_torque_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ipc_vcu_zrd_ipc_204_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_204_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->fl_wheel_speed, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->fl_wheel_speed, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->fl_wheel_speed, 16u, 0x01u);
    dst_p[2] |= pack_left_shift_u32(src_p->fr_wheel_speed, 1u, 0xfeu);
    dst_p[3] |= pack_right_shift_u32(src_p->fr_wheel_speed, 7u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->fr_wheel_speed, 15u, 0x03u);
    dst_p[4] |= pack_left_shift_u32(src_p->ml_wheel_speed, 2u, 0xfcu);
    dst_p[5] |= pack_right_shift_u32(src_p->ml_wheel_speed, 6u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->ml_wheel_speed, 14u, 0x07u);

    return (8);
}

int ipc_vcu_zrd_ipc_204_unpack(
    struct ipc_vcu_zrd_ipc_204_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fl_wheel_speed = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->fl_wheel_speed |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->fl_wheel_speed |= unpack_left_shift_u32(src_p[2], 16u, 0x01u);
    dst_p->fr_wheel_speed = unpack_right_shift_u32(src_p[2], 1u, 0xfeu);
    dst_p->fr_wheel_speed |= unpack_left_shift_u32(src_p[3], 7u, 0xffu);
    dst_p->fr_wheel_speed |= unpack_left_shift_u32(src_p[4], 15u, 0x03u);
    dst_p->ml_wheel_speed = unpack_right_shift_u32(src_p[4], 2u, 0xfcu);
    dst_p->ml_wheel_speed |= unpack_left_shift_u32(src_p[5], 6u, 0xffu);
    dst_p->ml_wheel_speed |= unpack_left_shift_u32(src_p[6], 14u, 0x07u);

    return (0);
}

int ipc_vcu_zrd_ipc_204_init(struct ipc_vcu_zrd_ipc_204_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_204_t));

    return 0;
}

uint32_t ipc_vcu_zrd_ipc_204_fl_wheel_speed_encode(double value)
{
    return (uint32_t)((value - -655.0) / 0.01);
}

double ipc_vcu_zrd_ipc_204_fl_wheel_speed_decode(uint32_t value)
{
    return (((double)value * 0.01) + -655.0);
}

bool ipc_vcu_zrd_ipc_204_fl_wheel_speed_is_in_range(uint32_t value)
{
    return (value <= 131071u);
}

uint32_t ipc_vcu_zrd_ipc_204_fr_wheel_speed_encode(double value)
{
    return (uint32_t)((value - -655.0) / 0.01);
}

double ipc_vcu_zrd_ipc_204_fr_wheel_speed_decode(uint32_t value)
{
    return (((double)value * 0.01) + -655.0);
}

bool ipc_vcu_zrd_ipc_204_fr_wheel_speed_is_in_range(uint32_t value)
{
    return (value <= 131071u);
}

uint32_t ipc_vcu_zrd_ipc_204_ml_wheel_speed_encode(double value)
{
    return (uint32_t)((value - -655.0) / 0.01);
}

double ipc_vcu_zrd_ipc_204_ml_wheel_speed_decode(uint32_t value)
{
    return (((double)value * 0.01) + -655.0);
}

bool ipc_vcu_zrd_ipc_204_ml_wheel_speed_is_in_range(uint32_t value)
{
    return (value <= 131071u);
}

int ipc_vcu_zrd_ipc_260_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_260_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->fault, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u16(src_p->vcu_sts, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->vcu_sts, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->car_start_state, 0u, 0x03u);
    dst_p[6] |= pack_left_shift_u16(src_p->vcu_service_voltage, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->vcu_service_voltage, 8u, 0xffu);

    return (8);
}

int ipc_vcu_zrd_ipc_260_unpack(
    struct ipc_vcu_zrd_ipc_260_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fault = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->vcu_sts = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->vcu_sts |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->car_start_state = unpack_right_shift_u8(src_p[3], 0u, 0x03u);
    dst_p->vcu_service_voltage = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->vcu_service_voltage |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int ipc_vcu_zrd_ipc_260_init(struct ipc_vcu_zrd_ipc_260_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_260_t));

    return 0;
}

uint8_t ipc_vcu_zrd_ipc_260_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_260_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_260_fault_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint16_t ipc_vcu_zrd_ipc_260_vcu_sts_encode(double value)
{
    return (uint16_t)(value);
}

double ipc_vcu_zrd_ipc_260_vcu_sts_decode(uint16_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_260_vcu_sts_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_260_car_start_state_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_260_car_start_state_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_260_car_start_state_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint16_t ipc_vcu_zrd_ipc_260_vcu_service_voltage_encode(double value)
{
    return (uint16_t)(value);
}

double ipc_vcu_zrd_ipc_260_vcu_service_voltage_decode(uint16_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_260_vcu_service_voltage_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int ipc_vcu_zrd_ipc_261_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_261_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->lv_main, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->lv_sun, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->lv_z_code, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u32(src_p->time, 0u, 0xffu);
    dst_p[4] |= pack_right_shift_u32(src_p->time, 8u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->time, 16u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->time, 24u, 0xffu);

    return (8);
}

int ipc_vcu_zrd_ipc_261_unpack(
    struct ipc_vcu_zrd_ipc_261_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->lv_main = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->lv_sun = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->lv_z_code = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->time = unpack_right_shift_u32(src_p[3], 0u, 0xffu);
    dst_p->time |= unpack_left_shift_u32(src_p[4], 8u, 0xffu);
    dst_p->time |= unpack_left_shift_u32(src_p[5], 16u, 0xffu);
    dst_p->time |= unpack_left_shift_u32(src_p[6], 24u, 0xffu);

    return (0);
}

int ipc_vcu_zrd_ipc_261_init(struct ipc_vcu_zrd_ipc_261_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_261_t));

    return 0;
}

uint8_t ipc_vcu_zrd_ipc_261_lv_main_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_261_lv_main_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_261_lv_main_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_261_lv_sun_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_261_lv_sun_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_261_lv_sun_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_261_lv_z_code_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_261_lv_z_code_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_261_lv_z_code_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint32_t ipc_vcu_zrd_ipc_261_time_encode(double value)
{
    return (uint32_t)(value);
}

double ipc_vcu_zrd_ipc_261_time_decode(uint32_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_261_time_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int ipc_vcu_zrd_ipc_203_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_203_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->brake_pressure1, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->brake_pressure1, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->brake_pressure2, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->brake_pressure2, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u8(src_p->curve_yk_max_speed, 0u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->soc, 0u, 0xffu);
    dst_p[7] |= pack_left_shift_u8(src_p->car_sts1, 0u, 0x03u);
    dst_p[7] |= pack_left_shift_u8(src_p->car_sts2, 2u, 0x0cu);

    return (8);
}

int ipc_vcu_zrd_ipc_203_unpack(
    struct ipc_vcu_zrd_ipc_203_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->brake_pressure1 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->brake_pressure1 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->brake_pressure2 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->brake_pressure2 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->curve_yk_max_speed = unpack_right_shift_u8(src_p[4], 0u, 0xffu);
    dst_p->soc = unpack_right_shift_u8(src_p[6], 0u, 0xffu);
    dst_p->car_sts1 = unpack_right_shift_u8(src_p[7], 0u, 0x03u);
    dst_p->car_sts2 = unpack_right_shift_u8(src_p[7], 2u, 0x0cu);

    return (0);
}

int ipc_vcu_zrd_ipc_203_init(struct ipc_vcu_zrd_ipc_203_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_203_t));

    return 0;
}

uint16_t ipc_vcu_zrd_ipc_203_brake_pressure1_encode(double value)
{
    return (uint16_t)(value / 0.05);
}

double ipc_vcu_zrd_ipc_203_brake_pressure1_decode(uint16_t value)
{
    return ((double)value * 0.05);
}

bool ipc_vcu_zrd_ipc_203_brake_pressure1_is_in_range(uint16_t value)
{
    return (value <= 200u);
}

uint16_t ipc_vcu_zrd_ipc_203_brake_pressure2_encode(double value)
{
    return (uint16_t)(value / 0.05);
}

double ipc_vcu_zrd_ipc_203_brake_pressure2_decode(uint16_t value)
{
    return ((double)value * 0.05);
}

bool ipc_vcu_zrd_ipc_203_brake_pressure2_is_in_range(uint16_t value)
{
    return (value <= 200u);
}

uint8_t ipc_vcu_zrd_ipc_203_curve_yk_max_speed_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_203_curve_yk_max_speed_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_203_curve_yk_max_speed_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_203_soc_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_203_soc_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_203_soc_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_203_car_sts1_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_203_car_sts1_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_203_car_sts1_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ipc_vcu_zrd_ipc_203_car_sts2_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_203_car_sts2_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_203_car_sts2_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

int ipc_vcu_zrd_ipc_202_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_202_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->fault1, 0u, 0xffu);
    dst_p[1] |= pack_left_shift_u8(src_p->fault2, 0u, 0xffu);
    dst_p[2] |= pack_left_shift_u8(src_p->fault3, 0u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->fault4, 0u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->mileage, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->mileage, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->mileage, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->mileage, 24u, 0xffu);

    return (8);
}

int ipc_vcu_zrd_ipc_202_unpack(
    struct ipc_vcu_zrd_ipc_202_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->fault1 = unpack_right_shift_u8(src_p[0], 0u, 0xffu);
    dst_p->fault2 = unpack_right_shift_u8(src_p[1], 0u, 0xffu);
    dst_p->fault3 = unpack_right_shift_u8(src_p[2], 0u, 0xffu);
    dst_p->fault4 = unpack_right_shift_u8(src_p[3], 0u, 0xffu);
    dst_p->mileage = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->mileage |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->mileage |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->mileage |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

int ipc_vcu_zrd_ipc_202_init(struct ipc_vcu_zrd_ipc_202_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_202_t));

    return 0;
}

uint8_t ipc_vcu_zrd_ipc_202_fault1_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_202_fault1_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_202_fault1_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_202_fault2_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_202_fault2_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_202_fault2_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_202_fault3_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_202_fault3_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_202_fault3_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_202_fault4_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_202_fault4_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_202_fault4_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

uint32_t ipc_vcu_zrd_ipc_202_mileage_encode(double value)
{
    return (uint32_t)(value / 0.1);
}

double ipc_vcu_zrd_ipc_202_mileage_decode(uint32_t value)
{
    return ((double)value * 0.1);
}

bool ipc_vcu_zrd_ipc_202_mileage_is_in_range(uint32_t value)
{
    return (value <= 9999999u);
}

int ipc_vcu_zrd_ipc_201_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_201_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->drive_mode, 0u, 0x03u);
    dst_p[0] |= pack_left_shift_u8(src_p->gear, 2u, 0x0cu);
    dst_p[0] |= pack_left_shift_u8(src_p->epo_sts, 4u, 0x30u);
    dst_p[0] |= pack_left_shift_u8(src_p->yk_h, 6u, 0x40u);
    dst_p[0] |= pack_left_shift_u8(src_p->yk_f, 7u, 0x80u);
    angle = (uint16_t)src_p->angle;
    dst_p[1] |= pack_left_shift_u16(angle, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(angle, 8u, 0xffu);
    dst_p[3] |= pack_left_shift_u8(src_p->flmcu_fatus, 0u, 0x01u);
    dst_p[3] |= pack_left_shift_u8(src_p->frmcu_fault, 1u, 0x02u);
    dst_p[3] |= pack_left_shift_u8(src_p->mlmcu_fault, 2u, 0x04u);
    dst_p[3] |= pack_left_shift_u8(src_p->mrmcu_fault, 3u, 0x08u);
    dst_p[3] |= pack_left_shift_u8(src_p->rlmcu_fault, 4u, 0x10u);
    dst_p[3] |= pack_left_shift_u8(src_p->rrmcu_fault, 5u, 0x20u);
    dst_p[3] |= pack_left_shift_u8(src_p->ebs1_fault, 6u, 0x40u);
    dst_p[3] |= pack_left_shift_u8(src_p->ebs2_fault, 7u, 0x80u);
    dst_p[4] |= pack_left_shift_u16(src_p->car_speed, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->car_speed, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->epb_lfr_sts, 0u, 0x0fu);
    dst_p[6] |= pack_left_shift_u8(src_p->epb_rfr_sts, 4u, 0xf0u);
    dst_p[7] |= pack_left_shift_u8(src_p->epb_ml_sts, 0u, 0x0fu);
    dst_p[7] |= pack_left_shift_u8(src_p->epb_mr_sts, 4u, 0xf0u);

    return (8);
}

int ipc_vcu_zrd_ipc_201_unpack(
    struct ipc_vcu_zrd_ipc_201_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->drive_mode = unpack_right_shift_u8(src_p[0], 0u, 0x03u);
    dst_p->gear = unpack_right_shift_u8(src_p[0], 2u, 0x0cu);
    dst_p->epo_sts = unpack_right_shift_u8(src_p[0], 4u, 0x30u);
    dst_p->yk_h = unpack_right_shift_u8(src_p[0], 6u, 0x40u);
    dst_p->yk_f = unpack_right_shift_u8(src_p[0], 7u, 0x80u);
    angle = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    angle |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    dst_p->angle = (int16_t)angle;
    dst_p->flmcu_fatus = unpack_right_shift_u8(src_p[3], 0u, 0x01u);
    dst_p->frmcu_fault = unpack_right_shift_u8(src_p[3], 1u, 0x02u);
    dst_p->mlmcu_fault = unpack_right_shift_u8(src_p[3], 2u, 0x04u);
    dst_p->mrmcu_fault = unpack_right_shift_u8(src_p[3], 3u, 0x08u);
    dst_p->rlmcu_fault = unpack_right_shift_u8(src_p[3], 4u, 0x10u);
    dst_p->rrmcu_fault = unpack_right_shift_u8(src_p[3], 5u, 0x20u);
    dst_p->ebs1_fault = unpack_right_shift_u8(src_p[3], 6u, 0x40u);
    dst_p->ebs2_fault = unpack_right_shift_u8(src_p[3], 7u, 0x80u);
    dst_p->car_speed = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->car_speed |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->epb_lfr_sts = unpack_right_shift_u8(src_p[6], 0u, 0x0fu);
    dst_p->epb_rfr_sts = unpack_right_shift_u8(src_p[6], 4u, 0xf0u);
    dst_p->epb_ml_sts = unpack_right_shift_u8(src_p[7], 0u, 0x0fu);
    dst_p->epb_mr_sts = unpack_right_shift_u8(src_p[7], 4u, 0xf0u);

    return (0);
}

int ipc_vcu_zrd_ipc_201_init(struct ipc_vcu_zrd_ipc_201_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_201_t));

    return 0;
}

uint8_t ipc_vcu_zrd_ipc_201_drive_mode_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_drive_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_drive_mode_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ipc_vcu_zrd_ipc_201_gear_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_gear_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ipc_vcu_zrd_ipc_201_epo_sts_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_epo_sts_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_epo_sts_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ipc_vcu_zrd_ipc_201_yk_h_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_yk_h_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_yk_h_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_201_yk_f_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_yk_f_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_yk_f_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int16_t ipc_vcu_zrd_ipc_201_angle_encode(double value)
{
    return (int16_t)(value);
}

double ipc_vcu_zrd_ipc_201_angle_decode(int16_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_201_flmcu_fatus_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_flmcu_fatus_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_flmcu_fatus_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_201_frmcu_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_frmcu_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_frmcu_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_201_mlmcu_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_mlmcu_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_mlmcu_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_201_mrmcu_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_mrmcu_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_mrmcu_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_201_rlmcu_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_rlmcu_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_rlmcu_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_201_rrmcu_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_rrmcu_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_rrmcu_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_201_ebs1_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_ebs1_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_ebs1_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_201_ebs2_fault_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_ebs2_fault_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_ebs2_fault_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint16_t ipc_vcu_zrd_ipc_201_car_speed_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double ipc_vcu_zrd_ipc_201_car_speed_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool ipc_vcu_zrd_ipc_201_car_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_201_epb_lfr_sts_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_epb_lfr_sts_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_epb_lfr_sts_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t ipc_vcu_zrd_ipc_201_epb_rfr_sts_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_epb_rfr_sts_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_epb_rfr_sts_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t ipc_vcu_zrd_ipc_201_epb_ml_sts_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_epb_ml_sts_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_epb_ml_sts_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

uint8_t ipc_vcu_zrd_ipc_201_epb_mr_sts_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_201_epb_mr_sts_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_201_epb_mr_sts_is_in_range(uint8_t value)
{
    return (value <= 15u);
}

int ipc_vcu_zrd_ipc_210_pack(
    uint8_t *dst_p,
    const struct ipc_vcu_zrd_ipc_210_t *src_p,
    size_t size)
{
    uint16_t target_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->domain_ctrl_epo, 3u, 0x08u);
    dst_p[0] |= pack_left_shift_u8(src_p->steering_mode, 4u, 0x10u);
    dst_p[0] |= pack_left_shift_u8(src_p->ipc_en, 5u, 0x20u);
    dst_p[0] |= pack_left_shift_u8(src_p->target_gear, 6u, 0xc0u);
    dst_p[1] |= pack_left_shift_u16(src_p->target_speed, 0u, 0xffu);
    dst_p[2] |= pack_right_shift_u16(src_p->target_speed, 8u, 0xffu);
    target_angle = (uint16_t)src_p->target_angle;
    dst_p[4] |= pack_left_shift_u16(target_angle, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(target_angle, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u8(src_p->brake_en, 0u, 0x01u);
    dst_p[6] |= pack_left_shift_u8(src_p->target_pressure, 1u, 0xfeu);
    dst_p[7] |= pack_left_shift_u8(src_p->dipped_lamp, 0u, 0x01u);
    dst_p[7] |= pack_left_shift_u8(src_p->turn_lamp, 1u, 0x06u);
    dst_p[7] |= pack_left_shift_u8(src_p->far_lamp, 3u, 0x08u);
    dst_p[7] |= pack_left_shift_u8(src_p->horn, 4u, 0x10u);
    dst_p[7] |= pack_left_shift_u8(src_p->car_off, 5u, 0x20u);
    dst_p[7] |= pack_left_shift_u8(src_p->alarm_lamp, 6u, 0x40u);
    dst_p[7] |= pack_left_shift_u8(src_p->out_line_lamp, 7u, 0x80u);

    return (8);
}

int ipc_vcu_zrd_ipc_210_unpack(
    struct ipc_vcu_zrd_ipc_210_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    uint16_t target_angle;

    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->domain_ctrl_epo = unpack_right_shift_u8(src_p[0], 3u, 0x08u);
    dst_p->steering_mode = unpack_right_shift_u8(src_p[0], 4u, 0x10u);
    dst_p->ipc_en = unpack_right_shift_u8(src_p[0], 5u, 0x20u);
    dst_p->target_gear = unpack_right_shift_u8(src_p[0], 6u, 0xc0u);
    dst_p->target_speed = unpack_right_shift_u16(src_p[1], 0u, 0xffu);
    dst_p->target_speed |= unpack_left_shift_u16(src_p[2], 8u, 0xffu);
    target_angle = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    target_angle |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->target_angle = (int16_t)target_angle;
    dst_p->brake_en = unpack_right_shift_u8(src_p[6], 0u, 0x01u);
    dst_p->target_pressure = unpack_right_shift_u8(src_p[6], 1u, 0xfeu);
    dst_p->dipped_lamp = unpack_right_shift_u8(src_p[7], 0u, 0x01u);
    dst_p->turn_lamp = unpack_right_shift_u8(src_p[7], 1u, 0x06u);
    dst_p->far_lamp = unpack_right_shift_u8(src_p[7], 3u, 0x08u);
    dst_p->horn = unpack_right_shift_u8(src_p[7], 4u, 0x10u);
    dst_p->car_off = unpack_right_shift_u8(src_p[7], 5u, 0x20u);
    dst_p->alarm_lamp = unpack_right_shift_u8(src_p[7], 6u, 0x40u);
    dst_p->out_line_lamp = unpack_right_shift_u8(src_p[7], 7u, 0x80u);

    return (0);
}

int ipc_vcu_zrd_ipc_210_init(struct ipc_vcu_zrd_ipc_210_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct ipc_vcu_zrd_ipc_210_t));

    return 0;
}

uint8_t ipc_vcu_zrd_ipc_210_domain_ctrl_epo_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_domain_ctrl_epo_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_domain_ctrl_epo_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_steering_mode_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_steering_mode_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_steering_mode_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_ipc_en_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_ipc_en_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_ipc_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_target_gear_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_target_gear_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_target_gear_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint16_t ipc_vcu_zrd_ipc_210_target_speed_encode(double value)
{
    return (uint16_t)(value / 0.1);
}

double ipc_vcu_zrd_ipc_210_target_speed_decode(uint16_t value)
{
    return ((double)value * 0.1);
}

bool ipc_vcu_zrd_ipc_210_target_speed_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

int16_t ipc_vcu_zrd_ipc_210_target_angle_encode(double value)
{
    return (int16_t)(value);
}

double ipc_vcu_zrd_ipc_210_target_angle_decode(int16_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_target_angle_is_in_range(int16_t value)
{
    (void)value;

    return (true);
}

uint8_t ipc_vcu_zrd_ipc_210_brake_en_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_brake_en_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_brake_en_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_target_pressure_encode(double value)
{
    return (uint8_t)(value / 0.1);
}

double ipc_vcu_zrd_ipc_210_target_pressure_decode(uint8_t value)
{
    return ((double)value * 0.1);
}

bool ipc_vcu_zrd_ipc_210_target_pressure_is_in_range(uint8_t value)
{
    return (value <= 60u);
}

uint8_t ipc_vcu_zrd_ipc_210_dipped_lamp_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_dipped_lamp_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_dipped_lamp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_turn_lamp_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_turn_lamp_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_turn_lamp_is_in_range(uint8_t value)
{
    return (value <= 3u);
}

uint8_t ipc_vcu_zrd_ipc_210_far_lamp_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_far_lamp_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_far_lamp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_horn_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_horn_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_horn_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_car_off_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_car_off_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_car_off_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_alarm_lamp_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_alarm_lamp_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_alarm_lamp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t ipc_vcu_zrd_ipc_210_out_line_lamp_encode(double value)
{
    return (uint8_t)(value);
}

double ipc_vcu_zrd_ipc_210_out_line_lamp_decode(uint8_t value)
{
    return ((double)value);
}

bool ipc_vcu_zrd_ipc_210_out_line_lamp_is_in_range(uint8_t value)
{
    return (value <= 1u);
}
