auto_heading_enable_dist_m: 1
can_name: can0
command_timeout_sec: 0.5
device_code: UAV-S-005
fcu_data_rate: 10
fcu_timeout: 5
fg_log_dir: logs/fg_log.jsonl
fix_yaw_dist: 1
follow_timeout: 1
go2_server_url: http://127.0.0.1:8444/api/push
heartbeat_hz: 0.5
is_omnidirectional: true
json_path: config/config.json
kd_xy: 0.10000000000000001
kd_yaw: 0.10000000000000001
kd_z: 0.10000000000000001
ki_xy: 0.01
ki_yaw: 0.01
ki_z: 0.01
kp_xy: 1.5
kp_yaw: 2
kp_z: 1
log_dir: logs/my_log.txt
loop_rate_hz: 50
mavsdk_url: tcp://127.0.0.1:5760
max_acc_xy: 1
max_acc_yaw: 2
max_acc_z: 0.80000000000000004
max_decel_xy: 1
max_decel_z: 0.80000000000000004
max_i_xy: 1
max_i_yaw: 1
max_i_z: 1
max_lookahead: 2.5
max_vel_xy: 3
max_vel_yaw: 1.5
max_vel_z: 1
min_lookahead: 0.5
mqtt_host: 192.168.2.14
mqtt_port: 41883
msg_interval_rate: 30
pdef_path: config/apm.pdef.xml
pos_tolerance: 1
pos_tolerance_m: 0.050000000000000003
posvel_timeout: 3
prearm_timeout: 3
report_alt_threshold: 0.050000000000000003
report_ang_threshold: 1
report_hz: 10
report_mission_hz: 1
report_pos_threshold: 0.050000000000000003
report_vel_threshold: 0.10000000000000001
server_port: 8000
static_dir: dist
takeoff_timeout: 100
udp_server_port: 9111
ui_config: drone-ui.yaml
yaw_full_speed_tol: 0.17000000000000001
yaw_tolerance: 0.080000000000000002
yaw_tolerance_rad: 0.050000000000000003
yaw_zero_speed_tol: 0.78000000000000003
z_tolerance: 1